Algoritmo "ExemploSE" //Nome do programa
VAR  //Definição das variáveis
   nome : CARACTERE;
   salario : REAL
INICIO
   escreva("Digite seu nome: ")
   leia(nome)
   escreva("Digite o salário: ")
   leia(salario)
   se (salario>1200) entao
       escreval(nome, " seu salário é maior que o salário mínimo!!!")
   senao
       escreval(nome, " seu salário é menor que o salário mínimo!!!")
    fimse
   Fimalgoritmo
       
